analytics:
  outputs:
    dev:
      dbname: postgres
      host: postgres
      pass: airflow
      port: 5432
      schema: analytics
      threads: 1
      type: postgres
      user: airflow
  target: dev
