version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: customer
      - name: invoice
      - name: invoiceline
      - name: track
      - name: album
      - name: artist
      - name: genre
